### ISSUE TITLE
about bug during training process

### ISSUE THREAD

**Issue by XuyangPan** [EuphoriaYan/zi2zi-pytorch#14]
您好，非常感谢您分享这个伟大项目，我在执行train.py时，遇到下面bug了，可以告知怎么解决吗？
unpickled total 13553 examples
Traceback (most recent call last):
  File "train.py", line 126, in <module>
    main()
  File "train.py", line 100, in main
    for bid, batch in enumerate(dataloader):
  File "/usr/python3.8/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/python3.8/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/python3.8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/python3.8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/source/code/panxy/src/FontGeneration/zi2zi/data/dataset.py", line 35, in __getitem__
    img_A, img_B = self.process(item[1])
  File "/source/code/panxy/src/FontGeneration/zi2zi/data/dataset.py", line 102, in process
    img_A = self.transform(img_A)
  File "/usr/python3.8/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 212, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/python3.8/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 298, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

**Comment by EuphoriaYan** [comment]
看起来是因为灰度/全彩图片的问题，请关注一下input_nc或者类似的参数~
我们当时试验了全彩图片，发现效果相当不好，所以后来就全部变成灰度图啦。

**Comment by XuyangPan** [comment]
parser.add_argument('--input_nc', type=int, default=3, help='number of input images channels')

是这个参数吗， 我的sample_dir下生成的图片是24位深度， 这里应该的 default=3  可以吗

**Comment by EuphoriaYan** [comment]
对，是这个参数；没记错的话，如果你这个参数改成1，读取图片时，会自动转换为灰度图的，不需要额外的改动；如果我记错了需要改动的话应该在读取图片那一块，加一个convert('L')即可。

**Comment by XuyangPan** [comment]
> 对，是这个参数；没记错的话，如果你这个参数改成1，读取图片时，会自动转换为灰度图的，不需要额外的改动；如果我记错了需要改动的话应该在读取图片那一块，加一个convert('L')即可。

非常感谢您的及时回复和解答！ train.py已经可以开始训练了

**Comment by EuphoriaYan** [comment]
好的，祝顺利！我close issue啦~

**Comment by XuyangPan** [comment]
我在执行package.py时，项目目录下没有dst_json文件，导致package.py未能成功运行，方便给dst_json文件吗
package.py里面的parser.add_argument('--dst_json', type=str, default=None)


再问一个，package.py和raw_package.py执行的功能是一样的吗
