### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by jilieryuyi** [EuphoriaYan/zi2zi-pytorch#25]
unpickled total 0 examples
unpickled total 8517 examples
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    main()
  File "train.py", line 102, in main
    for bid, batch in enumerate(dataloader):
  File "D:\PaddleGAN-venv\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\PaddleGAN-venv\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\PaddleGAN-venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\PaddleGAN-venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\code\zi2zi-pytorch-master\data\dataset.py", line 35, in __getitem__
    img_A, img_B = self.process(item[1])
  File "D:\code\zi2zi-pytorch-master\data\dataset.py", line 102, in process
    img_A = self.transform(img_A)
  File "D:\PaddleGAN-venv\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PaddleGAN-venv\lib\site-packages\torchvision\transforms\transforms.py", line 226, in forward

    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "D:\PaddleGAN-venv\lib\site-packages\torchvision\transforms\functional.py", line 351, in normali
ze
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

求教下，怎么调整？

**Comment by huakey** [comment]
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

求教下，怎么调整？ @jilieryuyi
