### ISSUE TITLE
'

### ISSUE THREAD

**Issue by Note-Liu** [EuphoriaYan/zi2zi-pytorch#30]

**Comment by ShellWen** [comment]
可以的

**Comment by Note-Liu** [comment]
> 可以的

Thanks

**Comment by Note-Liu** [comment]
> 可以的

我把10000张图片全部拼接成512 * 256的，命名为0_0.jpg到0_9999.jpg，然后package生成train.obj。训练的时候提示
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    main()
  File "train.py", line 107, in main
    const_loss, l1_loss, category_loss, cheat_loss = model.optimize_parameters()
  File "/home/code/zi2zi-pytorch/model/model.py", line 159, in optimize_parameters
    self.forward()  # compute fake images: G(A)
  File "/home/code/zi2zi-pytorch/model/model.py", line 100, in forward
    self.fake_B, self.encoded_real_A = self.netG(self.real_A, self.labels)
  File "/home/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/code/zi2zi-pytorch/model/generators.py", line 51, in forward
    return self.model(x, self.embedder(style_or_label))
  File "/home/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pytorch/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 147, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1913, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

这种情况请问你有遇到过吗
