### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by doublex640** [EuphoriaYan/zi2zi-pytorch#47]
按照视频教程一步一步来，软件版本都降级了，但还是出现错误，请大佬解惑！
Traceback (most recent call last):
  File "font2img.py", line 340, in <module>
    args.sample_count, args.sample_dir, args.label, args.filter)
  File "font2img.py", line 143, in font2font
    filter_hashes = set(filter_recurring_hash(charset, dst_font, canvas_size, x_offset, y_offset))
  File "font2img.py", line 131, in filter_recurring_hash
    hash_count[hash(img.tobytes())] += 1
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by doublex640** [comment]
解决了。已有字列表得是缺字的那个字体里导出的，而不是大而全的那个字体里的。我搞反了。

**Comment by fanabcd** [comment]
您好，我现在遇到了这个问题，请问具体，感激不尽
