### ISSUE TITLE
在第三部训练时出现AssertionError

### ISSUE THREAD

**Issue by doublex640** [EuphoriaYan/zi2zi-pytorch#48]
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    main()
  File "train.py", line 79, in main
    model.setup()
  File "F:\zi2zi-pytorch-master\model\model.py", line 59, in setup
    init_net(self.netG, gpu_ids=self.gpu_ids)
  File "F:\zi2zi-pytorch-master\utils\init_net.py", line 15, in init_net
    assert(torch.cuda.is_available())
AssertionError

**Comment by doublex640** [comment]
我的显卡是RTX660，可以支持cuda10.2

**Comment by doublex640** [comment]
问题出在cuda没有被调用，环境重新配置了一遍解决了
