### ISSUE TITLE
checkpoint文件夹不存在

### ISSUE THREAD

**Issue by hailongaa** [EuphoriaYan/zi2zi-pytorch#54]
Traceback (most recent call last):
  File "k:/ZiToZi/train.py", line 156, in <module>
    main()
  File "k:/ZiToZi/train.py", line 127, in main
    model.save_networks(global_steps)
  File "k:\ZiToZi\model\model.py", line 223, in save_networks
    torch.save(net.state_dict(), save_path)
  File "K:\Program Files\anaconda3\envs\py-37-Pytorch-cu117\lib\site-packages\torch\serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "K:\Program Files\anaconda3\envs\py-37-Pytorch-cu117\lib\site-packages\torch\serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "K:\Program Files\anaconda3\envs\py-37-Pytorch-cu117\lib\site-packages\torch\serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))  
RuntimeError: Parent directory K:\ZiToZi\训练\experiment_dir\checkpoint does not exist.  
错误是这个

**Comment by hailongaa** [comment]
搞定了。。。不能有中文路径
